### ISSUE TITLE
В настройках в самом начале прописать ссылку на GitHub

### ISSUE THREAD

**Issue by anvme** [ziemenz/Kinopoisk.bundle#14]
На следующих вкладках/страницах прописать ссылку на это репо, чтобы люди могли активнее писать о найденных багах
Настройки - Управление:Подключаемые модули - нажатие на шестеренку
Настройки - Настройки:Агенты Фильмы - Кинопоиск. В начале можно проставить информацию про это новое репо и просьбу постить инфузорным о найденных багах

**Comment by ziemenz** [comment]
Добавлено в релизе v2.0.7
