### ISSUE TITLE
Настройка вывода в описание рейтинга и слогана фильма

### ISSUE THREAD

**Issue by anvme** [ziemenz/Kinopoisk.bundle#7]
Original [http://kinoplex.reformal.ru/proj/?ia=1123485](http://kinoplex.reformal.ru/proj/?ia=1123485)
Сделать настройку вывода в описание рейтинга и слогана фильма
V Выводить в описание слоган фильма
V Выводить в описание рейтинг kinopoisk
V Выводить в описание рейтинг imdb
И выводить их каждый с новой строчки. И уже дальше описание фильма

**Comment by ziemenz** [comment]
Вынес в отдельные опции, версия v2.0.4
- Выводить в описание слоган фильма
- Выводить в описание рейтинг kinopoisk
- Выводить в описание рейтинг imdb
- Отображать количество проголосовавших в описании
- Выводить слоган и рейтинги каждый с новой строки

**Comment by anvme** [comment]
Есть предложение немного поправить строки и выводить рейтинг кино и imdb на одной строчке.  В вебе большая портянка выходит.
Соответственно:
- Выводить слоган и рейтинги на отдельных строчках в начале.

**Comment by ziemenz** [comment]
Сейчас нашел, что в метадате есть поле слоган, поиграюсь с ним и может не нужно будет вообще слоган в описание выводить
