### ISSUE TITLE
Возможность явно указать ID фильма/сериала

### ISSUE THREAD

**Issue by anvme** [ziemenz/Kinopoisk.bundle#9]
Original [http://kinoplex.reformal.ru/proj/?ia=1159995](http://kinoplex.reformal.ru/proj/?ia=1159995)
Например, в агенте Hama можно указать [tvdb-12345] в названии папки или файла и он гарантированно сопоставит с этим айди на твдб.

**Comment by Akior** [comment]
Желательно реализовать это в в виде:
manual match - подставим в название kinopoisk-1143242 - распарсит фильм https://www.kinopoisk.ru/film/1143242/
auto match - Мы можем сделать сканер который будет подставлять вместо имени фильма сразу же kinopoisk-1143242 ( например из полного названия "Джентльмены [The Gentlemen] (2019) [kinopoisk-1143242].mkv" ), Если же базовый сканер передаёт полное название "Джентльмены [The Gentlemen] (2019) [kinopoisk-1143242].mkv", то поиск kinopoisk-id на стороне агента
Лучше сразу возможность распознавания:
tvdb-id
tmdb-id
kinopoisk-id

**Comment by ziemenz** [comment]
Спасибо за уточнение, примерно так и планировалось сделать по-умолчанию.

Маркеры kp-1234567 и kinopoisk-1234567 будут работать по-умолчанию, этот маркер может быть как в имени файла, так и в названии папки, в которой он лежит, квадратные скобки не обязательно указывать

**Comment by ziemenz** [comment]
Если нужны поиск по tvdb-id и tmdb-id лучше их вынести в отдельные issue по каждому из агентов
